import Box from "@mui/material/Box";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import ReactQueryClientProvider from "./ReactQueryClientProvider";

export const metadata = {
  title: "Motilal Oswal Admin Utility",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <ThemeRegistry>
          <body>
            {/* <Header /> */}
            <Box>{children}</Box>
          </body>
        </ThemeRegistry>
      </html>
    </ReactQueryClientProvider>
  );
}
